Part3-Team15/taskify

.prettierignore
src/styles/globals.css
tailwind.config.ts

- #29 
피그마에 위와 같이 적혀있는데
아래와 같이 사용하시면 됩니다.
tailwindCss는 기본적으로 모바일 디폴트라서
CSS 작업하실 때,
모바일 먼저 작업하시고
태블릿은 md (min width 780)
데스크탑은 lg (min width 1280)
붙이고 하시면 됩니다.
브레이크 포인트는 일단 임의로 
**모바일** (779px 이하) 
**태블릿** (780px 이상 1279px 이하)
**데스크탑** (1280px 이상)
으로 설정해놨습니다. 
수정할 부분이나 여쭤볼 사항 있으면 리뷰 남겨주세요!
close #29

⚙️  Chore: tailwind 컬러 팔레트 및 반응형 브레이크 포인트 세팅

---

.eslintrc.json

⚙️ Chore: eslintrc.json 타입스크립트에 맞춰서 수정

---

src/containers/signin/SignInForm.tsx
src/hooks/useSignIn.ts
src/pages/_app.tsx
src/pages/signin/index.tsx
src/store/reducers/userSlice.ts
src/store/store.ts

- close #28 
- (**중요**⭐️) **다른 페이지 및 컴포넌트에서 유저 데이터를 사용하고 싶을 때, `useSelector`를 사용해 Redux store의 상태를 가져올 수 있습니다.** [예시](https://github.com/Part3-Team15/taskify/pull/43/files#r1649547935)
- useSignIn 커스텀 훅의 mutation 상태를 조정해 로그인 상태에 따른 로직을 구성할 수 있어요. (로그인 후 리다이렉트 처리 등등..)
- 로그아웃 기능 등 유저 데이터를 리셋하기 위해서는 1. `clearUser` 리듀서 사용 2. 로컬스토리지의 accessToken 삭제 방법 중에 선택하시면 됩니다.
- 로그인 폼은 테스트용으로 input만 있는 상태입니다. 자유롭게 변경하셔도 돼요.
- [Redux DevTools](https://chromewebstore.google.com/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=ko)를 설치하시는 걸 권장드립니다.

✨ Feat: 유저 기능 구현

---

src/hooks/useFetchData.ts

- close #54 
```ts
import { useState, useEffect } from 'react';
import { useSelector } from 'react-redux';
import { RootState } from '@/store/store';
const useFetchData = <T>(url: string) => {
const [data, setData] = useState<T | null>(null); // 제네릭 변수 T : 리스폰스 데이터 타입을 임의로 지정할 수 있음
const [isLoading, setIsLoading] = useState<boolean>(true);
const [error, setError] = useState<string | null>(null);
const accessToken = useSelector((state: RootState) => state.user.accessToken);
useEffect(() => {
const fetchData = async () => {
try {
const headers: HeadersInit = {};
if (accessToken) {
headers['Authorization'] = `Bearer ${accessToken}`; // 로그인 상태인 경우, 전역상태의 accessToken을 가져와 인증 요청을 할 수 있음
}
const response = await fetch(url, { headers });
if (!response.ok) {
throw new Error(`HTTP error! Status: …
```

✨ feat: useFetchData 커스텀 훅

---

src/utils/generateTagIndex.ts

- close #26 
- input: tag (string)
- output: index (number, 범위는 우리가 만들 태그 색상 개수, 현재는 16개)
- 내용: 글자들의 아스키 값 합을 색상 개수로 나눈 나머지를 인덱스로 하도록 구현했습니다.
- 해시 함수를 쓸 수 있지만, 추가로 라이브러리 사용해야 하는 것 같아서 아스키로 했습니다.
- <색상 개수>는 논의해서 지정하고, 컬러팔레트에서 tag-{idx}로 사용하면 좋을 것 같습니다.
- 만약 바로 hex 색상이 나왔으면 한다면, sha1 등으로 hash하고, 앞 6글자 이용하면 될 듯 합니다.
- sha1 예시: string -> ecb252044b5ea0f679ee78ec1a12904739e2904d -> ecb252
- 색이 예쁠지는 알 수 없지만 더 랜덤하게 이용 가능합니다.

✨ Feat: generateTagIndex 함수 구현

---

package.json
pnpm-lock.yaml
src/hooks/useFetchDashboards.ts
src/hooks/useFetchData.ts
src/services/axios.ts
src/services/getService.ts
src/store/reducers/dashboardsSlice.ts
src/store/store.ts
src/types/Dashboard.interface.ts

- close #58 
- close #52 
axios 인스턴스 정의 파일.** 로그인 된 경우, 자동으로 user(전역상태)의 accessToken 값을 헤더에 붙어 모든 유저 인증 요청이 가능함.
GET API 호출 함수 모음**
(예시로 컬럼 목록 조회(`getColumnsList()`), 대시보드 목록 조회(`getDashboardsList()`)만 일단 추가해두었습니다. 
- 대시보드 목록을 이제 전역 상태값으로 가져올 수 있어서, Header/Sidebar 구현하실 때 활용해주시면 감사하겠습니다 🙇‍♂️
- POST, PUT, DELETE API 함수 모음들도 `services/`에 구현해나가면 좋을 것 같아요!
- useSignin 커스텀훅도 대양님의 폼 작업이 마치면 리팩토링하겠습니다.

♻️ Refactor: 서비스 로직 분리 & useFetch 커스텀훅 리팩토링

---

.eslintrc.json
src/hooks/useSignIn.ts
src/store/reducers/userSlice.ts
src/types/User.interface.ts

- close #69
- User 타입 정의
- userSlice의 user에 정보 추가
- SigninResponse 에서 받는 정보도 추가
- .eslintrc.json에 import/typescript 플러그인 추가

✨ Feat: user 관련 저장하는 정보 추가 (이메일, 프로필 이미지)

---

src/containers/dashboard/ColumnsSection.tsx
src/containers/mydashboard/index.tsx
src/layouts/MainLayout.tsx

- #31
- 최대 크기 없앰
- 최소 너비 375px로 설정
- main 부분 배경색 지정 (페이지별로 각각 지정하던 것 삭제)
- 레이아웃에서 최대 크기 지정할 필요가 없는 것 같아서 삭제했습니다. (피그마에서 늘어나면 헤더는 계속 늘어남)
- 각자 섹션 크기가 고정된다면 내부에서 고정하면 될 것 같습니다.
- 배경색상을 레이아웃에서 지정해서 각 페이지에 있는 배경색 삭제했습니다.

🎨 design(#31): 레이아웃 크기, 색상 수정

---

package.json
pnpm-lock.yaml
src/hooks/useFetchDashboards.ts
src/hooks/useFetchData.ts
src/hooks/useSignIn.ts
src/pages/_app.tsx

- close #73 
ex) #이슈번호, #이슈번호
개발 환경에서 리액트 쿼리 개발자 툴을 보실 수 있습니다. 
추가 설명 사항은 코멘트로 남겨놓겠습니다!

⚙️ Chore: Tanstack Query 업그레이드

---

src/components/Modal/EmailExistModal.tsx
src/components/Modal/SignupSuccessModal.tsx
src/components/Modal/TextModal.tsx
src/components/Modal/index.tsx
src/constants/index.ts
src/containers/signin&signup/SignUpForm.tsx
src/pages/signup/index.tsx
src/types/Modal.interface.ts

- close #7
회원가입 성공 후 모달 열어서 확인 누르면 로그인 페이지로 이동하게 했습니다. 
확인 보다 로그인이 직관적일 것 같아서 일단 로그인이라고 해놨습니다!!
중복된 이메일 모달 나온 후에 email input에 focus 되고 값이 비워지면 좋겠는데,
시도해보다가 실패했습니다...🥲 추 후에 고려해보면 좋을 것 같아요

✨ Feat(#7): 회원가입 모달 연결

---

src/containers/mypage/PwdChangeForm.tsx

- close #118 
- 비밀번호 확인은 일치여부만 따지면 될 것 같아서 8자 이하 체크 하지 않았습니다!

🛠  Fix(#118): 새 비밀번호도 글자수 확인하도록 변경

---

package.json
pnpm-lock.yaml
src/components/Sidebar/index.tsx
src/containers/mydashboard/DashboardList/index.tsx
src/containers/mydashboard/InvitedDashboardList/index.tsx
src/containers/mydashboard/index.tsx
src/layouts/MainLayout.tsx
tailwind.config.ts

- close #124 
내 대시보드의 대시보드 목록에 스켈레톤 적용했습니다.
밑에 있는 대시보드 초대 목록은 스켈레톤 안했는데 하는게 더 좋을까요?
- 대시보드 초대 목록도 스켈레톤 추가 했습니다

🎨 design(#124): 내 대시보드 대시보드 목록 스켈레톤 설정

---

src/components/Header/DashboardHeader/index.tsx
src/components/Header/DefaultHeader.tsx
src/components/Header/LandingHeader.tsx
src/containers/dashboard/edit/DashboardEdit.tsx
src/layouts/MainLayout.tsx
src/pages/dashboard/[id]/edit.tsx

- close #40
틈새작업
- 나머지 내용 컴포넌트만 추가하면 됩니다!
- 자잘한 버튼/링크 때문에 페이지가 길고 더러워질 것 같아서, 페이지 내용을 컴포넌트로 뺐습니다.
- 모달 연결은 리팩토링 이후 한번에 작업하려고 합니다!

✨ feat(#40): 대시보드 수정페이지 완성

---

src/components/Modal/NewDashboardModal.tsx
src/containers/dashboard/edit/DashboardEdit.tsx
src/containers/dashboard/edit/DashboardModifySection.tsx
src/services/putService.ts
src/types/Dashboard.interface.ts

- close #25 
대시보드 수정 페이지에 대시보드 정보 수정 컴포넌트를 구현
API 관련 : 제가 구현한 대시보드 수정 컴포넌트는 수정 버튼 클릭 시 refetch 함수로 새로고침하는데 sidebar에 정보는 refetch가 안이루어지네요?! 사이드바랑 연동되면 좋을 것 같은데 어떻게 하면 될까요?!
반응형 관련 : 대시보드 이름이 길고, 뷰포트가 엄청나게 좁지 않으면 저렇게 컬러 선택 버튼이 그대로 있어도 괜찮은 것 같습니다.
혹시 다른 아이디어 있으면 얘기해주세용!!
그리고 저희가 설정한 tailwind-config color들 위와 같은 warning 나오네요?!

✨ Feat(#25): 대시보드 정보 수정 컴포넌트 추가

---

src/components/Sidebar/DashboardItem.tsx
src/components/Sidebar/index.tsx
src/containers/mydashboard/DashboardList/index.tsx
src/containers/mydashboard/InvitedDashboardList/index.tsx
src/containers/mydashboard/index.tsx
tailwind.config.ts

- close #129 
윈도우창 세로 크기를 줄이면 밑에 공간이 비어버리는 문제가 있어서 해결했습니다
사이드바에 스크롤을 넣었는데 스크롤바 생긴게 별로여서 tailwind-scrollbar-hide 플러그인 사용해서 숨겼습니다 있는게 더 나을까요?

🎨 design(#129): 화면 세로 크기를 줄이면 레이아웃이 고장나는 버그 수정

---

src/containers/mydashboard/InvitedDashboardList/Skeleton.tsx
src/containers/mydashboard/InvitedDashboardList/index.tsx

- close #158 
내 대시보드 스켈레톤에서 배열에 key값 중복 문제로 에러 콘솔이 나와서 배열을 지웠습니다

🛠  fix(#158): 내 대시보드 스켈레톤 key 문제 해결

---

src/hooks/useFetchData.ts

- close #77
- 잘못된 요청을 보내도 무한히 재요청 보내지 않게 횟수 제한했습니다.
https://github.com/Part3-Team15/taskify/assets/24778465/566e6eda-d8a1-4510-b4f3-236f2bd64cd5
https://github.com/Part3-Team15/taskify/assets/24778465/cdf0f3bf-6e2e-49b7-b8f0-8eaaa009f2c8
- 위에가 1회, 아래가 3회 재요청 제한을 건 모습입니다.
3회는 시간이 좀 오래걸려서 재요청 간격을 줄이거나 횟수를 줄이는 게 좋을 것 같습니다!
저는 1회여도 괜찮다고 보는데 다른 분들은 어떠신가요??
- 일단은 get에만 재요청 제한을 걸었습니다. 다른 요청은 큰 문제가 없었던 것 같아서요! (아마도 에러 핸들링을 해서..?)

🛠  Fix(#77): 재요청 횟수 제한

---

src/containers/dashboard/edit/DashboardModifySection.tsx
src/containers/signin&signup/SignUpForm.tsx

- close #185 
대시보드 생성 모달 코드이용해서
대시보드 관리에서 대시보드 이름 수정 시 15자 제한과 내용을 꼭 입력하도록 수정했습니다

🛠  fix(#185): 대시보드 이름 수정 시 15자 길이 제한

---

src/components/InviteNotice/index.tsx

- #168 
로그인 안해도 계속 대시보드 초대 확인을 해서 콘솔 에러가 나옵니다
로그인한 상태에서만 확인하도록 수정했습니다
@un0211 혜원님 이대로 해도 괜찮은지 확인해주세요! 🫡

🛠  fix(#168): 대시보드 초대 알림 문제 해결

---

src/pages/signin/index.tsx
src/pages/signup/index.tsx

- #171 
- 로그인/회원가입 위아래 여백설정했습니다.
|로그인|회원가입|
|-|-|
|<img width="498" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/c9133ab3-9b42-4f2f-ba34-290feb73aa9e">|<img width="359" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/32612a3e-1144-4bcc-ae85-c6e54e468fb2">|
|로그인|회원가입|
|-|-|
|<img width="445" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/96b1a6a1-a24e-4536-8158-85eca4d2e19c">|<img width="459" alt="image" src="https://github.com/Part3-Team15/taskify/assets/24778465/d51915f2-f9f9-46bf-a9ec-576c3bdce929">|
- 피그마 기반인데 너무 과한건 조금 줄였습니다. -> 얼마든지 다른값으로 변경하셔도 됩니다!
- 다른 디자인 수정사항도 추가로 올릴게요!

🎨 design(#171): 로그인/회원가입 여백설정

---

src/containers/dashboard/edit/MemberItem.tsx
src/styles/globals.css

- #24
대시보드 생성자 멤버 삭제 불가능하게 변경했습니다!!
글자색도 바꿨어요
다들 화이팅입니다!! 버그찾기 / 고치기 / 개선하기도 화이팅하고 마무리 정리도 잘해봐요~~

❗️ HOTFIX(#24): 대시보드 생성자 멤버 삭제 불가능하게 변경

---

src/containers/mydashboard/InvitedDashboardList/ItemList.tsx
src/containers/mydashboard/InvitedDashboardList/index.tsx

- close #200 
같은 대시보드 초대를 하나만 받을 수 있도록 수정
초대 받은 대시보드와 같은 대시보드는 수락을 했을때 나머지는 전부 거절하게 만들었습니다

🛠  fix(#200): 같은 대시보드 초대를 하나만 받을 수 있도록 수정

---

src/containers/dashboard/edit/index.tsx

- #153
- 다크모드로 대시보드 삭제 버튼색상이 바뀌었는데 원상복귀했습니다!

🛠  Fix(#153): 다크모드로 바뀐 버튼 디자인 복귀

---

src/components/InviteNotice/index.tsx

- #198
- 첫 번째 알람에도 초대가 올 수 있게 초기값을 null로 변경하고, 결과가 제대로 왔을 때 실제 배열로 초기화했습니다.

🛠  fix(#198): 첫 번째 초대도 알람 올 수 있게 변경
